### ISSUE TITLE
Molpay is not working in IOS version

### ISSUE THREAD

**Issue by muhzi4u** [MOLPay/molpay-mobile-xdk-cordova#3]
I have added the plugin using the command

`cordova plugin add molpay-mobile-xdk-cordova`

It is working in android version perfectly , but not working in ios version.

**Android**
![whatsapp image 2017-06-01 at 3 23 39 pm](https://cloud.githubusercontent.com/assets/12408980/26674571/83ac761e-46de-11e7-8282-57ff7957b078.jpeg)

**IOS**
![whatsapp image 2017-06-01 at 3 24 07 pm](https://cloud.githubusercontent.com/assets/12408980/26674578/8d8c0b40-46de-11e7-8665-b9b01f52e11c.jpeg)

Close button only coming.Also i am not getting any error  .Please help me on this?

**Comment by clewlb** [comment]
@muhzi4u, please open a support ticket with our support at support@molpay.com, so we can help you through your issues. Thanks.
