### ISSUE TITLE
Advanced phone validation failed

### ISSUE THREAD

**Issue by ridwan85** [MOLPay/molpay-mobile-xdk-cordova#4]
Hi i tested with this phone number on IOS

```
60386669101 - works
67386669101 - doesnt work
63386669101 - doesnt work
```

I think the xdk only accept 60 country code of malaysia only. Where as other country will throw this error

`{Error: "Advanced phone validation failed"}`

FYI, for mobile-xdk-android and website seamless all can accept numbers other than 60

**Comment by clewlb** [comment]
@ridwan85,

// Optional, enable this for extended phone format validation based on Google i18n standards.
'mp_advanced_phone_validation_enabled': true

67386669101 and 63386669101 is not validated in the Google i18n standards. So it will fail if you opted the "mp_advanced_phone_validation_enabled" option.

So, please opt out "mp_advanced_phone_validation_enabled" if you want to just accept any phone number formats.
